### ISSUE TITLE
About the reproducibility of results

### ISSUE THREAD

**Issue by chenghuang66** [autonomousvision/plant#11]
Thanks for your amazing work! Currently, i download your checkpoints and follow your instruction to test plant in Longest6 benchmark. However, i could not reproduce the performance of PlnaT in Table I in your artcle.  The average results of PlanTSubmission experiment I got are as follows: DS= 27.62, IS=0.53, RC=  60.11.  The average results of PlanTSubmission_map experiment I got are as follows: DS= 55.54, IS=0.71, RC=  80.03. These results are far lower than those in the paper (Sensors: DS= 57.66, IS=0.65, RC=  88.2; Privileged: DS=81.36, RC=93.55, IS=0.87 ) .  I only change user in config.yaml. Specially, i found the ego car will go to the reverse lane at the begining of longest_weathers_10, as shown in picture.  I am very confused about this.  Hope to receive your reply.

![image](https://user-images.githubusercontent.com/41883629/212313751-f3322631-f323-4930-8149-8db1f1786baf.png)

**Comment by chenghuang66** [comment]
I'm very sorry, my partner has reproduced the results.

**Comment by changjiahao** [comment]
I have encountered a similar situation. Have you resolved it?
