### ISSUE TITLE
Question about tokenization of routes

### ISSUE THREAD

**Issue by indranilmaji** [autonomousvision/plant#13]
Hello, 
I am interested to know which part of the codebase , tokenizes the routes obtained from carla using Ramer-Douglas-Peucker algorithm. Thank you.

**Comment by kashyap7x** [comment]
We tokenize the route during data generation. It is implemented in this block of code, using the `rdp` package:
https://github.com/autonomousvision/plant/blob/1bfb695910d816e70f53521aa263648072edea8e/carla_agent_files/data_agent_boxes.py#L393
