### ISSUE TITLE
Perception only training

### ISSUE THREAD

**Issue by Mahgoobi** [autonomousvision/plant#19]
I have reviewed the code to some degree, but I can't seem to find how to train the perception part independently. There is some implementations in the code for data collection etc.., but there doesn't seem to be loop closing when it comes to training perception or defining the perception task.

e.g. not implemented 
https://github.com/autonomousvision/plant/blob/main/training/dataloader.py#L46

no used
https://github.com/autonomousvision/plant/blob/main/training/Perception/config.py#L79

Maybe the code is incomplete? Please let me know. Thanks in advance.

**Comment by RenzKa** [comment]
Hi,
thanks for your interest. Yes we did not release the training code for the perception part.
We used this repository as starting point for the training: https://github.com/autonomousvision/transfuser
