### ISSUE TITLE
Questions about data and pre-trained model downloads

### ISSUE THREAD

**Issue by swb19** [autonomousvision/plant#5]
Hello, when I tried to download the model and data using `download.sh` and `download_data.sh`, I found that the provided links seem to be invalid. Could you please provide a new download link? Thank you very much.

**Comment by RenzKa** [comment]
Hi,

can you try again if it works now?

**Comment by RenzKa** [comment]
Hi,
we currently don't plan to upload the dataset with sensor data. However, we have uploaded code to collect the dataset with sensor data.

The dataset should be the same in terms of content. But we made some changes in coordinate systems and how we save and load the data. So it is not possible to use the original dataset of Transfuser. But our dataset is collected on exactly the same routes and scenarios.

**Comment by SiyuanHuang95** [comment]
Hi,

Thanks for your update! All clear!
